import type { Writer, Order, Payment, ChartData, FileAttachment } from './types'

export const mockWriters: Writer[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@example.com',
    role: 'writer',
    status: 'active',
    tasksCompleted: 45,
    pendingTasks: 3,
    inRevision: 1,
    currentActiveTask: 'Research Paper on Climate Change',
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'Michael Chen',
    email: 'michael.chen@example.com',
    role: 'writer',
    status: 'active',
    tasksCompleted: 67,
    pendingTasks: 2,
    inRevision: 0,
    currentActiveTask: 'Business Case Study Analysis',
    createdAt: '2024-02-20',
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    email: 'emily.rodriguez@example.com',
    role: 'writer',
    status: 'active',
    tasksCompleted: 23,
    pendingTasks: 4,
    inRevision: 2,
    createdAt: '2024-03-10',
  },
  {
    id: '4',
    name: 'David Kim',
    email: 'david.kim@example.com',
    role: 'writer',
    status: 'inactive',
    tasksCompleted: 89,
    pendingTasks: 0,
    inRevision: 0,
    createdAt: '2023-11-05',
  },
  {
    id: '5',
    name: 'Amanda Foster',
    email: 'amanda.foster@example.com',
    role: 'writer',
    status: 'active',
    tasksCompleted: 34,
    pendingTasks: 5,
    inRevision: 1,
    currentActiveTask: 'Marketing Strategy Essay',
    createdAt: '2024-04-01',
  },
]

export const mockOrders: Order[] = [
  {
    id: '1',
    title: 'Research Paper on Climate Change',
    description: 'A comprehensive research paper analyzing the effects of climate change on coastal ecosystems.',
    status: 'in_progress',
    price: 150,
    deadline: '2026-04-15',
    assignedWriterId: '1',
    assignedWriter: mockWriters[0],
    createdAt: '2026-03-01',
    updatedAt: '2026-03-10',
    attachments: [
      {
        id: 'att-1',
        name: 'research_guidelines.pdf',
        size: 245000,
        type: 'application/pdf',
        url: '#',
        uploadedAt: '2026-03-01',
      },
      {
        id: 'att-2',
        name: 'reference_materials.docx',
        size: 1200000,
        type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        url: '#',
        uploadedAt: '2026-03-01',
      },
    ],
  },
  {
    id: '2',
    title: 'Business Case Study Analysis',
    description: 'Analysis of Tesla business model and market strategy.',
    status: 'in_progress',
    price: 200,
    deadline: '2026-04-20',
    assignedWriterId: '2',
    assignedWriter: mockWriters[1],
    createdAt: '2026-03-05',
    updatedAt: '2026-03-12',
  },
  {
    id: '3',
    title: 'Literature Review - Modern Poetry',
    description: 'A literature review covering major themes in 21st century poetry.',
    status: 'pending',
    price: 120,
    deadline: '2026-04-25',
    createdAt: '2026-03-08',
    updatedAt: '2026-03-08',
  },
  {
    id: '4',
    title: 'Marketing Strategy Essay',
    description: 'Essay on effective digital marketing strategies for small businesses.',
    status: 'revision',
    price: 180,
    deadline: '2026-04-10',
    assignedWriterId: '5',
    assignedWriter: mockWriters[4],
    createdAt: '2026-02-20',
    updatedAt: '2026-03-18',
    comments: [
      {
        id: '1',
        orderId: '4',
        userId: 'admin1',
        userName: 'Admin',
        content: 'Please expand the section on social media marketing.',
        createdAt: '2026-03-18',
      },
    ],
  },
  {
    id: '5',
    title: 'Technical Documentation',
    description: 'API documentation for a SaaS application.',
    status: 'completed',
    price: 250,
    deadline: '2026-03-15',
    assignedWriterId: '2',
    assignedWriter: mockWriters[1],
    createdAt: '2026-02-15',
    updatedAt: '2026-03-14',
  },
  {
    id: '6',
    title: 'Psychology Research Essay',
    description: 'Research essay on cognitive behavioral therapy effectiveness.',
    status: 'pending',
    price: 175,
    deadline: '2026-05-01',
    createdAt: '2026-03-20',
    updatedAt: '2026-03-20',
  },
  {
    id: '7',
    title: 'History Essay - World War II',
    description: 'Detailed essay on the economic impacts of World War II.',
    status: 'cancelled',
    price: 130,
    deadline: '2026-03-30',
    createdAt: '2026-02-25',
    updatedAt: '2026-03-05',
  },
  {
    id: '8',
    title: 'Philosophy Thesis Chapter',
    description: 'A chapter on existentialism in modern philosophy.',
    status: 'completed',
    price: 300,
    deadline: '2026-03-20',
    assignedWriterId: '4',
    assignedWriter: mockWriters[3],
    createdAt: '2026-02-01',
    updatedAt: '2026-03-19',
  },
]

export const mockPayments: Payment[] = [
  {
    id: '1',
    orderId: '5',
    orderTitle: 'Technical Documentation',
    writerId: '2',
    writerName: 'Michael Chen',
    amount: 250,
    status: 'paid',
    paidAt: '2026-03-16',
    createdAt: '2026-03-14',
  },
  {
    id: '2',
    orderId: '8',
    orderTitle: 'Philosophy Thesis Chapter',
    writerId: '4',
    writerName: 'David Kim',
    amount: 300,
    status: 'paid',
    paidAt: '2026-03-21',
    createdAt: '2026-03-19',
  },
  {
    id: '3',
    orderId: '1',
    orderTitle: 'Research Paper on Climate Change',
    writerId: '1',
    writerName: 'Sarah Johnson',
    amount: 150,
    status: 'pending',
    createdAt: '2026-03-10',
  },
  {
    id: '4',
    orderId: '2',
    orderTitle: 'Business Case Study Analysis',
    writerId: '2',
    writerName: 'Michael Chen',
    amount: 200,
    status: 'pending',
    createdAt: '2026-03-12',
  },
  {
    id: '5',
    orderId: '7',
    orderTitle: 'History Essay - World War II',
    writerId: '3',
    writerName: 'Emily Rodriguez',
    amount: 130,
    status: 'cancelled',
    createdAt: '2026-03-05',
  },
]

export const mockChartData: ChartData[] = [
  { date: 'Jan', tasks: 25, completed: 20 },
  { date: 'Feb', tasks: 32, completed: 28 },
  { date: 'Mar', tasks: 45, completed: 38 },
  { date: 'Apr', tasks: 38, completed: 32 },
  { date: 'May', tasks: 52, completed: 45 },
  { date: 'Jun', tasks: 48, completed: 42 },
]

export const adminMetrics = {
  totalTasks: mockOrders.length,
  assignedTasks: mockOrders.filter((o) => o.assignedWriterId).length,
  pendingTasks: mockOrders.filter((o) => o.status === 'pending').length,
  completedTasks: mockOrders.filter((o) => o.status === 'completed').length,
}

export const writerMetrics = {
  completedOrders: 45,
  pendingOrders: 3,
  inRevision: 1,
  cancelledOrders: 2,
}

export const paymentMetrics = {
  totalPaid: mockPayments.filter((p) => p.status === 'paid').reduce((sum, p) => sum + p.amount, 0),
  totalPending: mockPayments.filter((p) => p.status === 'pending').reduce((sum, p) => sum + p.amount, 0),
  totalCancelled: mockPayments.filter((p) => p.status === 'cancelled').reduce((sum, p) => sum + p.amount, 0),
}
